version: '3.7'
services:
    rabbitmq:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: rabbitMQ-lab
        restart: always
        ports:
            - "15672:15672"
            - "5672:5672"
        hostname: rabbit_host
        # volumes:
        #     - ./data/:/var/lib/rabbitmq
        environment: 
            RABBITMQ_DEFAULT_USER: test
            RABBITMQ_DEFAULT_PASS: test
            RABBITMQ_VM_MEMORY_WATERMARK: 0.5
        networks:
            - rabbit_network
networks:
    rabbit_network: